openapi: 3.0.3
info:
  title: Weather Server
  description: Weather Server API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      summary: Query the service status.
      description: Use this endpoint to retrieve information about the health of the service.
      tags:
        - Meta
      responses:
        200:
          description: The service is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
        500:
          description: The service is experiencing a critical error.
